version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    environment:
        - JEKYLL_ENV=docker
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
    container_name: taylex 